name: CI

on: [push, pull_request]

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
           with:
              fetch-depth: 0 # Fetch all history
         - uses: actions/setup-node@v3
           with:
              node-version-file: '.nvmrc'
         - run: npm ci
         - run: npm run standards
         - run: npm run build
         - uses: actions/upload-pages-artifact@v3
           with:
              path: 'dist/'
   deploy:
      if: github.ref == 'refs/heads/master'
      needs: build
      permissions:
         pages: write
         id-token: write
      environment:
         name: github-pages
         url: ${{ steps.deployment.outputs.page_url }}
      runs-on: ubuntu-latest
      steps:
         - name: Deploy to GitHub Pages
           uses: actions/deploy-pages@v4
